version: "3.9"

services:
  auth:
    build: .
    image: auth
    container_name: auth_container
    command: gunicorn wsgi_app:app -b 0.0.0.0:5000 --reload
    user: web
    ports:
      - "5000:5000"
    depends_on:
      - db
      - redis
    env_file:
      - .env

  db:
    image: postgres:13
    container_name: db_container
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env

  redis:
    image: redis:6.2.5
    container_name: redis_container
    ports:
      - "6379:6379"

volumes:
  postgres_data:
    name: postgres_data