version: "3.9"

services:
  auth:
    build: .
    image: auth
    user: web
    ports:
      - "5000:5000"

  db:
    image: postgres:13
    ports:
      - "5432:5432"

  redis:
    image: redis:6.2.5
    ports:
      - "6379:6379"
